export enum ACTION_TYPES {
  BOOK_WS_REQUEST = 'BOOK_WS_REQUEST',
  BOOK_WS_INFO = 'BOOK_WS_INFO',
  BOOK_WS_SUBSCRIBED = 'BOOK_WS_SUBSCRIBED',
  BOOK_WS_SNAPSHOT = 'BOOK_WS_SNAPSHOT',
  BOOK_WS_MESSAGE = 'BOOK_WS_MESSAGE',
  BOOK_WS_CLOSE = 'BOOK_WS_CLOSE'
}

export const PRECISION_TYPES = ['P0', 'P1', 'P2', 'P3', 'P4'];
