export enum ACTION_TYPES {
  BOOK_WS_REQUEST = 'BOOK_WS_REQUEST',
  BOOK_WS_CLOSE = 'BOOK_WS_CLOSE',
  BOOK_WS_ON_MESSAGE = 'BOOK_WS_ON_MESSAGE'
}

export const PRECISION_TYPES = ['P0', 'P1', 'P2', 'P3', 'P04'];
