export enum ACTION_TYPES {
  TICKER_WS_REQUEST = 'TICKER_WS_REQUEST',
  TICKER_WS_INFO = 'TICKER_WS_INFO',
  TICKER_WS_SUBSCRIBED = 'TICKER_WS_SUBSCRIBED',
  TICKER_WS_MESSAGE = 'TICKER_WS_MESSAGE'
}
