export enum ACTION_TYPES {
  TRADES_WS_REQUEST = 'TRADES_WS_REQUEST',
  TRADES_WS_INFO = 'TRADES_WS_INFO',
  TRADES_WS_SUBSCRIBED = 'TRADES_WS_SUBSCRIBED',
  TRADES_WS_SNAPSHOT = 'TRADES_WS_SNAPSHOT',
  TRADES_WS_MESSAGE = 'TRADES_WS_MESSAGE'
}
